### ISSUE TITLE
Linking products and SKUs

### ISSUE THREAD

**Issue by all9lives** [njosefbeck/gatsby-source-stripe#1]
I'm building some e-commerce functionality, pulling product data from stripe. Is there a way to link products and skus together? Since we need to pull information like description etc from the product API and things like price etc from the SKU api. 

Ideally we could make a query like this.
```graphql
{
  allStripeSku {
    edges {
      node {
        id
        active
        price
        products {
          id
          name
          description
        }	
      }
    }
  }
}
```

Is something like this possible, or would I need to chain several queries to get the product which belongs to a sku?

**Comment by njosefbeck** [comment]
Hello!

Currently this isn't possible, but I'm looking into setting it up so that all Stripe objects would be auto-expanded: https://stripe.com/docs/api#expanding_objects. This would then allow you to get the full product information under a sku. I'll update this issue once I've finished updating my code.

**Comment by njosefbeck** [comment]
@all9lives - So I think I've successfully got this working. I've tested it and it works locally. Feel free to `npm install gatsby-source-stripe` the latest version and let me know if you run into any issues: https://www.npmjs.com/package/gatsby-source-stripe

**Comment by all9lives** [comment]
@njosefbeck Thanks for adding that in, it works great.
