### ISSUE TITLE
Solution: found 1 vulnerability requiring 1 manual review (.nvmrc)

### ISSUE THREAD

**Issue by ronnlidd** [njosefbeck/gatsby-source-stripe#18]
### Description

Dependency of gatsby-source-stripe not working

### Steps to Reproduce

1. Deploy app with gatsby-source-stripe as plugin

### Solution

1. Add .nvmrc file with node version specified. Like this: 
[.NVMRC FILE EXAMPLE](https://github.com/thorsten-stripe/ecommerce-gatsby-tutorial/blob/master/.nvmrc
)

**Comment by njosefbeck** [comment]
Hi @ronnlidd ,

Thanks for bringing this to my attention. `gatsby-source-stripe` will run on versions of Node greater than v10. Is Thorsten using .nvmrc because he experienced an error when trying to deploy his site to Netlify? 

Also, the following question needs to be answered, before adding a .nvmrc file to this project.

(1) Does Netlify respect .nvmrc files in dependencies installed and found in the node_modules folder? I.e. will it look for all the .nvmrc files in node_modules and then make sure it installs the proper version? I just thought it would look for a .nvmrc file at the root of the project.

Currently in the README we specify that `gatsby-source-stripe` needs Node v.10 or above to run properly, so depending on the answer to the above question, we could add language saying that a person should add a `.nvmrc` file to the root of their project, linking to Thorsten's example.

**Comment by ronnlidd** [comment]
Hey, yes, in my understanding it has to be in the root of the project but I'm not certain. Thanks for your work!

**Comment by njosefbeck** [comment]
Sorry for the delay in response. I think that instead of adding a .nvmrc file to this project, it would make more sense to add an [engines key](https://docs.npmjs.com/files/package.json#engines) to our package.json.

Then, in the README, we can also add language recommending that someone should add a `.nvmrc` file to their Gatsby project, specifying a Node version in the v.10 range.

**Comment by njosefbeck** [comment]
Added engines key in v2.2.0!
