### ISSUE TITLE
Products with recurring payment not shown on Gatsby shop

### ISSUE THREAD

**Issue by mcneiljv** [njosefbeck/gatsby-source-stripe#47]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
  * Read through the README fully
  * Ensured you are running Node v.10 or above
  * Made sure you're using at least Gatsby v.2.0.15
  * Checked that your issue isn't already filed

### Description

I'm trying to use this plugin to set up a Gatsby storefront for my company. However, we want our products to be subscription-based. The one time payment products show up fine, but the ones with recurring payments fail to show up on the storefront even after I stop my localhost and start it up again.

### Steps to Reproduce

1. Add product to Stripe with recurring payment
2. Close local server and restart
3. The recurring payment product does not show up

**Expected behavior:** The recurring payment product should show up on the store along with the one time payment products

**Actual behavior:** The recurring payment product does not show up.

**Reproduces how often:** 100% of the time

### Versions

os: MacOS High Sierra 10.13.6
node: v10.7.0
npm: 6.14.2
gatsby: Gatsby CLI version: 2.8.22
gatsby-source-stripe: 2.2.2

### Additional Information

None.

**Comment by njosefbeck** [comment]
Hi Jamie!

First, yay for using Gatsby for your company's storefront! That's awesome!  Also, sorry to hear that you're having this issue.

I just did a test and was able to get back both products of type `good` and `service` from Stripe using `gatsby-source-stripe`. For this test I was using the latest version of my plugin ([3.0.6](https://www.npmjs.com/package/gatsby-source-stripe)).

My gatsby config for this plugin looked like:
```javascript
{
  resolve: `gatsby-source-stripe`,
  options: {
    objects: ['Product'],
    secretKey: ***,
    }
}
```
My GraphQL query and results looked like:

<img width="629" alt="Screen Shot 2020-03-11 at 2 00 01 PM" src="https://user-images.githubusercontent.com/9508002/76453291-9db4a400-63a0-11ea-94f9-51a81d300cf9.png" />

Some initial thoughts that you could try:
- Upgrade to the latest version of the plugin and try again.
- See if you can hit the Stripe API directly for products and get back the `service` ones.

One thing I did notice is that if you're trying to query for SKUs, since `service` products don't have SKUs, it's not going to return those products with that query.

Let me know if any of the above helps! If not, we can do more digging.

**Comment by mcneiljv** [comment]
Ah! See, I'm only getting the allStripeSku and stripeSku options in graphql currently. I will update and post here with my findings! Thanks.

**Comment by mcneiljv** [comment]
I updated my plugin and that did it! Thanks a ton for your help. Closing this issue.

**Comment by njosefbeck** [comment]
Yay wonderful! I'm so glad it worked. I'll make a note to update the README to include a "Gotchas" section for things like this.

Also, I'd love to feature your site in the plugin's README once it's live, so be sure to be in touch! Thanks!
